# Generated by Django 5.1.4 on 2025-01-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_emotion_sentences_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='pos_index',
            field=models.IntegerField(default=0),
        ),
    ]
