# Generated by Django 5.1.4 on 2025-01-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_words_article_id_words_pos_index_words_sentence_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case1', models.TextField()),
                ('case2', models.TextField()),
                ('case3', models.TextField()),
            ],
        ),
    ]
