# Generated by Django 5.1.4 on 2025-01-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test_cases',
        ),
    ]
