# Generated by Django 5.1.4 on 2025-01-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_rename_test_test_cases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_cases',
            new_name='TestCases',
        ),
    ]
